ALTER FUNCTION registrar_usuario(VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, NUMERIC)
SECURITY DEFINER
SET search_path = public, extensions;

ALTER FUNCTION login(VARCHAR, VARCHAR, INET, TEXT)
SECURITY DEFINER
SET search_path = public, extensions;
